#!/bin/bash

if [ ! -z $1 ]; then
    RESTART_CHANNEL_ID="-r $1"
fi

echo $RESTART_CHANNEL_ID

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [ $USER == 'ubuntu' ]; then
	git pull origin master
else
	echo "Not on prod!"
fi

source bin/activate
pip install -r requirements.txt

if [ ! -d "logs" ]; then
	mkdir logs
fi

ts=$(date +%s)
pkill -f "python3 turkish_delight_bot.py"
python3 turkish_delight_bot.py $RESTART_CHANNEL_ID &

echo "Plat-bot running."
